spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/payments}
spring.datasource.username=${DB_USERNAME:payments}
spring.datasource.password=${DB_PASSWORD:payments_local_dev}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
